name: Callee

on:
  workflow_call:
    inputs:
      releaseToPlayStore:
        required: true
        type: boolean
      releaseToFirebase:
        required: true
        type: boolean
    secrets:
      apple_connect_email:
        required: false
    outputs:
      output1:
        description: "The build artifact name"
        value: ${{ inputs.releaseToPlayStore }}
      output2:
        description: "The app bundle id"
        value: ${{ inputs.releaseToFirebase }}

jobs:

  release_to_playsrore:
    name: Release to the Play Store / Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Add Google Play Authentication
        if: ${{ inputs.releaseToPlayStore }}
        run: echo ${{ inputs.releaseToPlayStore }}

      - name: Add Firebase Authentication
        if: ${{ inputs.releaseToFirebase }}
        run: echo ${{ inputs.releaseToFirebase }}

      - name: Check Secret Exists
        env:
         APPLE_CONNECT_EMAIL: ${{ secrets.apple_connect_email }}
        if: ${{ env.APPLE_CONNECT_EMAIL != '' }}
        run: echo ${{ env.APPLE_CONNECT_EMAIL }}
