name: Callee

on:
  workflow_call:
    inputs:
      releaseToPlayStore:
        required: true
        type: boolean
      releaseToFirebase:
        required: true
        type: boolean
      isDevelopmentBuild:
        required: false
        type: boolean
        default: true
    secrets:
      apple_connect_email:
        required: false

jobs:

  release_to_playsrore:
    name: Release to the Play Store / Firebase
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Get Current Time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
         format: x

      - name: Add Google Play Authentication
        if: ${{ inputs.releaseToPlayStore }}
        run: echo ${{ inputs.releaseToPlayStore }}

      - name: Add Firebase Authentication
        if: ${{ inputs.releaseToFirebase }}
        run: echo ${{ inputs.releaseToFirebase }}

      - name: Check Secret Exists
        env:
         APPLE_CONNECT_EMAIL: ${{ secrets.apple_connect_email }}
        if: ${{ env.APPLE_CONNECT_EMAIL != '' }}
        run: echo ${{ env.APPLE_CONNECT_EMAIL }}

      - name: Check Is Development Build
        if: ${{ inputs.isDevelopmentBuild }}
        run: echo ${{ inputs.isDevelopmentBuild }}

      - name: Current Time
        run: echo ${{ steps.current-time.outputs.formattedTime }}
